/* Simulation code for SimpleSwitchTest generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */
#if !defined(SimpleSwitchTest__MODEL_H)
#define SimpleSwitchTest__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "SimpleSwitchTest_functions.h"


extern void SimpleSwitchTest_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void SimpleSwitchTest_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int SimpleSwitchTest_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_checkForAsserts(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int SimpleSwitchTest_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* SimpleSwitchTest_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* SimpleSwitchTest_relationDescription(int i);
extern void SimpleSwitchTest_function_initSample(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleSwitchTest_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleSwitchTest_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleSwitchTest_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleSwitchTest_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleSwitchTest_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleSwitchTest_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleSwitchTest_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleSwitchTest_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleSwitchTest_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleSwitchTest_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleSwitchTest_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleSwitchTest_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleSwitchTest_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* SimpleSwitchTest_linear_model_frame(void);
extern const char* SimpleSwitchTest_linear_model_datarecovery_frame(void);
extern int SimpleSwitchTest_mayer(DATA* data, modelica_real** res, short *);
extern int SimpleSwitchTest_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int SimpleSwitchTest_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int SimpleSwitchTest_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int SimpleSwitchTest_setInputData(DATA *data, const modelica_boolean file);
extern int SimpleSwitchTest_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void SimpleSwitchTest_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void SimpleSwitchTest_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int SimpleSwitchTest_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void SimpleSwitchTest_read_simulation_info(SIMULATION_INFO* simulationData);
extern void SimpleSwitchTest_read_input_fmu(MODEL_DATA* modelData);
extern void SimpleSwitchTest_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int SimpleSwitchTest_inputNames(DATA* data, char ** names);
extern int SimpleSwitchTest_dataReconciliationInputNames(DATA* data, char ** names);
extern int SimpleSwitchTest_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int SimpleSwitchTest_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int SimpleSwitchTest_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int SimpleSwitchTest_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "SimpleSwitchTest_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(SimpleSwitchTest__MODEL_H) */


