#include "simulation_data.h"
#include "util/real_array.h"

OMC_DISABLE_OPT

void SimpleSwitchTest_read_simulation_info(SIMULATION_INFO* simulationInfo)
{
  simulationInfo->startTime = 0.0;
  simulationInfo->stopTime = 10.0;
  simulationInfo->stepSize = 0.02;
  simulationInfo->tolerance = 1e-6;
  simulationInfo->solverMethod = "dassl";
  simulationInfo->outputFormat = "mat";
  simulationInfo->variableFilter = ".*";
  simulationInfo->OPENMODELICAHOME = "C:/Program Files/OpenModelica1.26.3-64bit";
}

void SimpleSwitchTest_read_input_fmu(MODEL_DATA* modelData)
{
  modelData->realVarsData[0].info.id = 1000;
  modelData->realVarsData[0].info.name = "der($outputAlias_outputVoltage)";
  modelData->realVarsData[0].info.comment = "Measures the voltage on the resistor";
  modelData->realVarsData[0].info.info.filename = "SimpleSwitchTest";
  modelData->realVarsData[0].info.info.lineStart = 4;
  modelData->realVarsData[0].info.info.colStart = 3;
  modelData->realVarsData[0].info.info.lineEnd = 4;
  modelData->realVarsData[0].info.info.colEnd = 93;
  modelData->realVarsData[0].info.info.readonly = 0;
  modelData->realVarsData[0].attribute.unit = "";
  modelData->realVarsData[0].attribute.displayUnit = "";
  modelData->realVarsData[0].attribute.min = -DBL_MAX;
  modelData->realVarsData[0].attribute.max = DBL_MAX;
  modelData->realVarsData[0].attribute.fixed = 0;
  modelData->realVarsData[0].attribute.useNominal = 0;
  modelData->realVarsData[0].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[0].attribute.start);
  modelData->realVarsData[1].info.id = 1001;
  modelData->realVarsData[1].info.name = "$outputAlias_outputVoltage";
  modelData->realVarsData[1].info.comment = "Measures the voltage on the resistor";
  modelData->realVarsData[1].info.info.filename = "SimpleSwitchTest";
  modelData->realVarsData[1].info.info.lineStart = 4;
  modelData->realVarsData[1].info.info.colStart = 3;
  modelData->realVarsData[1].info.info.lineEnd = 4;
  modelData->realVarsData[1].info.info.colEnd = 93;
  modelData->realVarsData[1].info.info.readonly = 0;
  modelData->realVarsData[1].attribute.unit = "";
  modelData->realVarsData[1].attribute.displayUnit = "";
  modelData->realVarsData[1].attribute.min = -DBL_MAX;
  modelData->realVarsData[1].attribute.max = DBL_MAX;
  modelData->realVarsData[1].attribute.fixed = 0;
  modelData->realVarsData[1].attribute.useNominal = 0;
  modelData->realVarsData[1].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[1].attribute.start);
  modelData->realVarsData[2].info.id = 1002;
  modelData->realVarsData[2].info.name = "$outputVoltage_der";
  modelData->realVarsData[2].info.comment = "";
  modelData->realVarsData[2].info.info.filename = "";
  modelData->realVarsData[2].info.info.lineStart = 0;
  modelData->realVarsData[2].info.info.colStart = 0;
  modelData->realVarsData[2].info.info.lineEnd = 0;
  modelData->realVarsData[2].info.info.colEnd = 0;
  modelData->realVarsData[2].info.info.readonly = 0;
  modelData->realVarsData[2].attribute.unit = "";
  modelData->realVarsData[2].attribute.displayUnit = "";
  modelData->realVarsData[2].attribute.min = -DBL_MAX;
  modelData->realVarsData[2].attribute.max = DBL_MAX;
  modelData->realVarsData[2].attribute.fixed = 0;
  modelData->realVarsData[2].attribute.useNominal = 0;
  modelData->realVarsData[2].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[2].attribute.start);
  modelData->realVarsData[3].info.id = 1003;
  modelData->realVarsData[3].info.name = "Ground.p.i";
  modelData->realVarsData[3].info.comment = "Current flowing into the pin";
  modelData->realVarsData[3].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/Pin.mo";
  modelData->realVarsData[3].info.info.lineStart = 9;
  modelData->realVarsData[3].info.info.colStart = 3;
  modelData->realVarsData[3].info.info.lineEnd = 14;
  modelData->realVarsData[3].info.info.colEnd = 61;
  modelData->realVarsData[3].info.info.readonly = 0;
  modelData->realVarsData[3].attribute.unit = "A";
  modelData->realVarsData[3].attribute.displayUnit = "";
  modelData->realVarsData[3].attribute.min = -DBL_MAX;
  modelData->realVarsData[3].attribute.max = DBL_MAX;
  modelData->realVarsData[3].attribute.fixed = 1;
  modelData->realVarsData[3].attribute.useNominal = 0;
  modelData->realVarsData[3].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[3].attribute.start);
  modelData->realVarsData[4].info.id = 1004;
  modelData->realVarsData[4].info.name = "Ground.p.v";
  modelData->realVarsData[4].info.comment = "Potential at the pin";
  modelData->realVarsData[4].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/Pin.mo";
  modelData->realVarsData[4].info.info.lineStart = 3;
  modelData->realVarsData[4].info.info.colStart = 3;
  modelData->realVarsData[4].info.info.lineEnd = 8;
  modelData->realVarsData[4].info.info.colEnd = 61;
  modelData->realVarsData[4].info.info.readonly = 0;
  modelData->realVarsData[4].attribute.unit = "V";
  modelData->realVarsData[4].attribute.displayUnit = "";
  modelData->realVarsData[4].attribute.min = -DBL_MAX;
  modelData->realVarsData[4].attribute.max = DBL_MAX;
  modelData->realVarsData[4].attribute.fixed = 1;
  modelData->realVarsData[4].attribute.useNominal = 0;
  modelData->realVarsData[4].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[4].attribute.start);
  modelData->realVarsData[5].info.id = 1005;
  modelData->realVarsData[5].info.name = "Resistor.LossPower";
  modelData->realVarsData[5].info.comment = "Loss power leaving component via heatPort";
  modelData->realVarsData[5].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/ConditionalHeatPort.mo";
  modelData->realVarsData[5].info.info.lineStart = 13;
  modelData->realVarsData[5].info.info.colStart = 3;
  modelData->realVarsData[5].info.info.lineEnd = 13;
  modelData->realVarsData[5].info.info.colEnd = 65;
  modelData->realVarsData[5].info.info.readonly = 0;
  modelData->realVarsData[5].attribute.unit = "W";
  modelData->realVarsData[5].attribute.displayUnit = "";
  modelData->realVarsData[5].attribute.min = -DBL_MAX;
  modelData->realVarsData[5].attribute.max = DBL_MAX;
  modelData->realVarsData[5].attribute.fixed = 0;
  modelData->realVarsData[5].attribute.useNominal = 0;
  modelData->realVarsData[5].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[5].attribute.start);
  modelData->realVarsData[6].info.id = 1006;
  modelData->realVarsData[6].info.name = "Resistor.R_actual";
  modelData->realVarsData[6].info.comment = "Actual resistance = R*(1 + alpha*(T_heatPort - T_ref))";
  modelData->realVarsData[6].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Basic/Resistor.mo";
  modelData->realVarsData[6].info.info.lineStart = 11;
  modelData->realVarsData[6].info.info.colStart = 3;
  modelData->realVarsData[6].info.info.lineEnd = 12;
  modelData->realVarsData[6].info.info.colEnd = 61;
  modelData->realVarsData[6].info.info.readonly = 0;
  modelData->realVarsData[6].attribute.unit = "Ohm";
  modelData->realVarsData[6].attribute.displayUnit = "";
  modelData->realVarsData[6].attribute.min = -DBL_MAX;
  modelData->realVarsData[6].attribute.max = DBL_MAX;
  modelData->realVarsData[6].attribute.fixed = 1;
  modelData->realVarsData[6].attribute.useNominal = 0;
  modelData->realVarsData[6].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[6].attribute.start);
  modelData->realVarsData[7].info.id = 1007;
  modelData->realVarsData[7].info.name = "Resistor.i";
  modelData->realVarsData[7].info.comment = "Current flowing from pin p to pin n";
  modelData->realVarsData[7].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/OnePort.mo";
  modelData->realVarsData[7].info.info.lineStart = 5;
  modelData->realVarsData[7].info.info.colStart = 3;
  modelData->realVarsData[7].info.info.lineEnd = 5;
  modelData->realVarsData[7].info.info.colEnd = 53;
  modelData->realVarsData[7].info.info.readonly = 0;
  modelData->realVarsData[7].attribute.unit = "A";
  modelData->realVarsData[7].attribute.displayUnit = "";
  modelData->realVarsData[7].attribute.min = -DBL_MAX;
  modelData->realVarsData[7].attribute.max = DBL_MAX;
  modelData->realVarsData[7].attribute.fixed = 0;
  modelData->realVarsData[7].attribute.useNominal = 0;
  modelData->realVarsData[7].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[7].attribute.start);
  modelData->realVarsData[8].info.id = 1008;
  modelData->realVarsData[8].info.name = "Sensor.n.i";
  modelData->realVarsData[8].info.comment = "Current flowing into the pin";
  modelData->realVarsData[8].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/NegativePin.mo";
  modelData->realVarsData[8].info.info.lineStart = 9;
  modelData->realVarsData[8].info.info.colStart = 3;
  modelData->realVarsData[8].info.info.lineEnd = 14;
  modelData->realVarsData[8].info.info.colEnd = 61;
  modelData->realVarsData[8].info.info.readonly = 0;
  modelData->realVarsData[8].attribute.unit = "A";
  modelData->realVarsData[8].attribute.displayUnit = "";
  modelData->realVarsData[8].attribute.min = -DBL_MAX;
  modelData->realVarsData[8].attribute.max = DBL_MAX;
  modelData->realVarsData[8].attribute.fixed = 1;
  modelData->realVarsData[8].attribute.useNominal = 0;
  modelData->realVarsData[8].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[8].attribute.start);
  modelData->realVarsData[9].info.id = 1009;
  modelData->realVarsData[9].info.name = "Sensor.p.i";
  modelData->realVarsData[9].info.comment = "Current flowing into the pin";
  modelData->realVarsData[9].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/PositivePin.mo";
  modelData->realVarsData[9].info.info.lineStart = 9;
  modelData->realVarsData[9].info.info.colStart = 3;
  modelData->realVarsData[9].info.info.lineEnd = 14;
  modelData->realVarsData[9].info.info.colEnd = 61;
  modelData->realVarsData[9].info.info.readonly = 0;
  modelData->realVarsData[9].attribute.unit = "A";
  modelData->realVarsData[9].attribute.displayUnit = "";
  modelData->realVarsData[9].attribute.min = -DBL_MAX;
  modelData->realVarsData[9].attribute.max = DBL_MAX;
  modelData->realVarsData[9].attribute.fixed = 1;
  modelData->realVarsData[9].attribute.useNominal = 0;
  modelData->realVarsData[9].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[9].attribute.start);
  modelData->realVarsData[10].info.id = 1010;
  modelData->realVarsData[10].info.name = "outputVoltage";
  modelData->realVarsData[10].info.comment = "Measures the voltage on the resistor";
  modelData->realVarsData[10].info.info.filename = "SimpleSwitchTest";
  modelData->realVarsData[10].info.info.lineStart = 4;
  modelData->realVarsData[10].info.info.colStart = 3;
  modelData->realVarsData[10].info.info.lineEnd = 4;
  modelData->realVarsData[10].info.info.colEnd = 93;
  modelData->realVarsData[10].info.info.readonly = 0;
  modelData->realVarsData[10].attribute.unit = "";
  modelData->realVarsData[10].attribute.displayUnit = "";
  modelData->realVarsData[10].attribute.min = -DBL_MAX;
  modelData->realVarsData[10].attribute.max = DBL_MAX;
  modelData->realVarsData[10].attribute.fixed = 0;
  modelData->realVarsData[10].attribute.useNominal = 0;
  modelData->realVarsData[10].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realVarsData[10].attribute.start);
  /* AHEU 1 */
  modelData->realParameterData[0].info.id = 1011;
  modelData->realParameterData[0].info.name = "BooleanToRealConverter.realFalse";
  modelData->realParameterData[0].info.comment = "Output signal for false Boolean input";
  modelData->realParameterData[0].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Blocks/Math.mo";
  modelData->realParameterData[0].info.info.lineStart = 2010;
  modelData->realParameterData[0].info.info.colStart = 5;
  modelData->realParameterData[0].info.info.lineEnd = 2010;
  modelData->realParameterData[0].info.info.colEnd = 73;
  modelData->realParameterData[0].info.info.readonly = 0;
  modelData->realParameterData[0].attribute.unit = "";
  modelData->realParameterData[0].attribute.displayUnit = "";
  modelData->realParameterData[0].attribute.min = -DBL_MAX;
  modelData->realParameterData[0].attribute.max = DBL_MAX;
  modelData->realParameterData[0].attribute.fixed = 1;
  modelData->realParameterData[0].attribute.useNominal = 0;
  modelData->realParameterData[0].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realParameterData[0].attribute.start);
  modelData->realParameterData[1].info.id = 1012;
  modelData->realParameterData[1].info.name = "BooleanToRealConverter.realTrue";
  modelData->realParameterData[1].info.comment = "Output signal for true Boolean input";
  modelData->realParameterData[1].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Blocks/Math.mo";
  modelData->realParameterData[1].info.info.lineStart = 2009;
  modelData->realParameterData[1].info.info.colStart = 5;
  modelData->realParameterData[1].info.info.lineEnd = 2009;
  modelData->realParameterData[1].info.info.colEnd = 71;
  modelData->realParameterData[1].info.info.readonly = 0;
  modelData->realParameterData[1].attribute.unit = "";
  modelData->realParameterData[1].attribute.displayUnit = "";
  modelData->realParameterData[1].attribute.min = -DBL_MAX;
  modelData->realParameterData[1].attribute.max = DBL_MAX;
  modelData->realParameterData[1].attribute.fixed = 1;
  modelData->realParameterData[1].attribute.useNominal = 0;
  modelData->realParameterData[1].attribute.nominal = 1.0;
  put_real_element(5.0, 0, &modelData->realParameterData[1].attribute.start);
  modelData->realParameterData[2].info.id = 1013;
  modelData->realParameterData[2].info.name = "Resistor.R";
  modelData->realParameterData[2].info.comment = "Resistance at temperature T_ref";
  modelData->realParameterData[2].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Basic/Resistor.mo";
  modelData->realParameterData[2].info.info.lineStart = 3;
  modelData->realParameterData[2].info.info.colStart = 3;
  modelData->realParameterData[2].info.info.lineEnd = 4;
  modelData->realParameterData[2].info.info.colEnd = 38;
  modelData->realParameterData[2].info.info.readonly = 0;
  modelData->realParameterData[2].attribute.unit = "Ohm";
  modelData->realParameterData[2].attribute.displayUnit = "";
  modelData->realParameterData[2].attribute.min = -DBL_MAX;
  modelData->realParameterData[2].attribute.max = DBL_MAX;
  modelData->realParameterData[2].attribute.fixed = 1;
  modelData->realParameterData[2].attribute.useNominal = 0;
  modelData->realParameterData[2].attribute.nominal = 1.0;
  put_real_element(100.0, 0, &modelData->realParameterData[2].attribute.start);
  modelData->realParameterData[3].info.id = 1014;
  modelData->realParameterData[3].info.name = "Resistor.T";
  modelData->realParameterData[3].info.comment = "Fixed device temperature if useHeatPort = false";
  modelData->realParameterData[3].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/ConditionalHeatPort.mo";
  modelData->realParameterData[3].info.info.lineStart = 7;
  modelData->realParameterData[3].info.info.colStart = 3;
  modelData->realParameterData[3].info.info.lineEnd = 8;
  modelData->realParameterData[3].info.info.colEnd = 97;
  modelData->realParameterData[3].info.info.readonly = 0;
  modelData->realParameterData[3].attribute.unit = "K";
  modelData->realParameterData[3].attribute.displayUnit = "degC";
  modelData->realParameterData[3].attribute.min = 0.0;
  modelData->realParameterData[3].attribute.max = DBL_MAX;
  modelData->realParameterData[3].attribute.fixed = 1;
  modelData->realParameterData[3].attribute.useNominal = 1;
  modelData->realParameterData[3].attribute.nominal = 300.0;
  put_real_element(0.0, 0, &modelData->realParameterData[3].attribute.start);
  modelData->realParameterData[4].info.id = 1015;
  modelData->realParameterData[4].info.name = "Resistor.T_heatPort";
  modelData->realParameterData[4].info.comment = "Temperature of heatPort";
  modelData->realParameterData[4].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/ConditionalHeatPort.mo";
  modelData->realParameterData[4].info.info.lineStart = 14;
  modelData->realParameterData[4].info.info.colStart = 3;
  modelData->realParameterData[4].info.info.lineEnd = 14;
  modelData->realParameterData[4].info.info.colEnd = 54;
  modelData->realParameterData[4].info.info.readonly = 0;
  modelData->realParameterData[4].attribute.unit = "K";
  modelData->realParameterData[4].attribute.displayUnit = "degC";
  modelData->realParameterData[4].attribute.min = 0.0;
  modelData->realParameterData[4].attribute.max = DBL_MAX;
  modelData->realParameterData[4].attribute.fixed = 1;
  modelData->realParameterData[4].attribute.useNominal = 1;
  modelData->realParameterData[4].attribute.nominal = 300.0;
  put_real_element(0.0, 0, &modelData->realParameterData[4].attribute.start);
  modelData->realParameterData[5].info.id = 1016;
  modelData->realParameterData[5].info.name = "Resistor.T_ref";
  modelData->realParameterData[5].info.comment = "Reference temperature";
  modelData->realParameterData[5].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Basic/Resistor.mo";
  modelData->realParameterData[5].info.info.lineStart = 5;
  modelData->realParameterData[5].info.info.colStart = 3;
  modelData->realParameterData[5].info.info.lineEnd = 5;
  modelData->realParameterData[5].info.info.colEnd = 64;
  modelData->realParameterData[5].info.info.readonly = 0;
  modelData->realParameterData[5].attribute.unit = "K";
  modelData->realParameterData[5].attribute.displayUnit = "degC";
  modelData->realParameterData[5].attribute.min = 0.0;
  modelData->realParameterData[5].attribute.max = DBL_MAX;
  modelData->realParameterData[5].attribute.fixed = 1;
  modelData->realParameterData[5].attribute.useNominal = 1;
  modelData->realParameterData[5].attribute.nominal = 300.0;
  put_real_element(300.15, 0, &modelData->realParameterData[5].attribute.start);
  modelData->realParameterData[6].info.id = 1017;
  modelData->realParameterData[6].info.name = "Resistor.alpha";
  modelData->realParameterData[6].info.comment = "Temperature coefficient of resistance (R_actual = R*(1 + alpha*(T_heatPort - T_ref))";
  modelData->realParameterData[6].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Basic/Resistor.mo";
  modelData->realParameterData[6].info.info.lineStart = 6;
  modelData->realParameterData[6].info.info.colStart = 3;
  modelData->realParameterData[6].info.info.lineEnd = 7;
  modelData->realParameterData[6].info.info.colEnd = 91;
  modelData->realParameterData[6].info.info.readonly = 0;
  modelData->realParameterData[6].attribute.unit = "1/K";
  modelData->realParameterData[6].attribute.displayUnit = "";
  modelData->realParameterData[6].attribute.min = -DBL_MAX;
  modelData->realParameterData[6].attribute.max = DBL_MAX;
  modelData->realParameterData[6].attribute.fixed = 1;
  modelData->realParameterData[6].attribute.useNominal = 0;
  modelData->realParameterData[6].attribute.nominal = 1.0;
  put_real_element(0.0, 0, &modelData->realParameterData[6].attribute.start);
  modelData->booleanVarsData[0].info.id = 1018;
  modelData->booleanVarsData[0].info.name = "switchOn";
  modelData->booleanVarsData[0].info.comment = "If true, power is on";
  modelData->booleanVarsData[0].info.info.filename = "SimpleSwitchTest";
  modelData->booleanVarsData[0].info.info.lineStart = 3;
  modelData->booleanVarsData[0].info.info.colStart = 3;
  modelData->booleanVarsData[0].info.info.lineEnd = 3;
  modelData->booleanVarsData[0].info.info.colEnd = 74;
  modelData->booleanVarsData[0].info.info.readonly = 0;
  modelData->booleanVarsData[0].attribute.fixed = 1;
  modelData->booleanVarsData[0].attribute.start = 0;
  modelData->booleanParameterData[0].info.id = 1019;
  modelData->booleanParameterData[0].info.name = "Resistor.useHeatPort";
  modelData->booleanParameterData[0].info.comment = "= true, if heatPort is enabled";
  modelData->booleanParameterData[0].info.info.filename = "C:/Users/pedro/AppData/Roaming/.openmodelica/libraries/Modelica 4.1.0+maint.om/Electrical/Analog/Interfaces/ConditionalHeatPort.mo";
  modelData->booleanParameterData[0].info.info.lineStart = 5;
  modelData->booleanParameterData[0].info.info.colStart = 3;
  modelData->booleanParameterData[0].info.info.lineEnd = 6;
  modelData->booleanParameterData[0].info.info.colEnd = 69;
  modelData->booleanParameterData[0].info.info.readonly = 0;
  modelData->booleanParameterData[0].attribute.fixed = 1;
  modelData->booleanParameterData[0].attribute.start = 0;
}